<p><strong>Подвиг 3.</strong> Имеется следующий фрагмент программы:</p>

<pre><code>try:
    val = float(input())
except ValueError as e:
    print(e)
else:
    val *= 10
    print(val)
finally:
    print("finally")</code></pre>

<p>При каких входных данных выполнение программы перейдет в блок finally?</p>