<p><strong>Подвиг 2.</strong> Имеется следующий фрагмент программы:</p>

<pre><code>try:
    val = float(input())
except ValueError as e:
    print(e)</code></pre>

<p>При каких входных данных выполнение программы перейдет в блок except?</p>